### ISSUE TITLE
Meu Cadastro : Interface do cliente

### ISSUE THREAD

**Issue by Irapoam** [rhenter/venda-online#24]
- Histórico de Compras
- Últimas Compras
- Pedidos em aberto

**Comment by rhenter** [comment]
@rebeccamno Conseguiu fechar essa tarefa ?

**Comment by rebeccamno** [comment]
não , pois falta a parte de controle de pedidos

**Comment by rhenter** [comment]
Separei as tarefas e criei um ticket para cada.

Estou fechando este ticket pois voce ja fez a interface do cliente
